import type { Metadata } from 'next';
import '@/app/globals.css';
import { Poppins } from 'next/font/google';
import { Providers } from '@/app/providers';
import NextTopLoader from 'nextjs-toploader';
import { Toaster } from '@/components/ui/sonner';

const poppins = Poppins({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>): JSX.Element {
	return (
		<html lang='en'>
			<body className={`${poppins.className} antialiased`}>
				<NextTopLoader
					color='#17a34a'
					initialPosition={0.08}
					crawlSpeed={200}
					height={3}
					easing='ease'
					speed={200}
					shadow='0 0 10px #17a34a,0 0 5px #17a34a'
				/>
				<Providers>
					{children}
					<Toaster closeButton richColors position='top-right' />
				</Providers>
			</body>
		</html>
	);
}
