name: QR Dine - CLIENT Continous Integration

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node and Bun
        run: |
          # Set up Node.js
          echo "Setting up Node.js"
          npm install -g bun
          
      - name: Install dependencies
        run: bun install

      - name: Set up environment variables
        id: set-env
        run: |
          echo "NEXT_PUBLIC_ADMIN_URL=${{ secrets.NEXT_PUBLIC_ADMIN_URL }}" >> $GITHUB_ENV

      - name: Run Lint
        run: bun run lint

      - name: Run Format Check
        run: bun run format

      - name: Build with Next.js
        run: bun run build
