name: QR Dine - CLIENT Continous Integration

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node and Yarn
        run: |
          # Set up Node.js
          echo "Setting up Node.js"
          npm i -g yarn
          
      - name: Install dependencies
        run: yarn install

      - name: Set up environment variables
        id: set-env
        run: |
          echo "NEXT_PUBLIC_ADMIN_URL=${{ secrets.NEXT_PUBLIC_ADMIN_URL }}" >> $GITHUB_ENV

      - name: Run Lint
        run: yarn run lint

      - name: Run Format Check
        run: yarn run format

      - name: Build with Next.js
        run: yarn run build
